// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKTjrbKau6NEfLEF-o_FWT_BYsMzogtYQ',
    appId: '1:32942490702:web:1f7164d88579a6abaa2f1f',
    messagingSenderId: '32942490702',
    projectId: 'accompani-app',
    authDomain: 'accompani-app.firebaseapp.com',
    storageBucket: 'accompani-app.appspot.com',
    measurementId: 'G-VVC35N9JJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkpOyQsq3U8iSWZgUkDelz7DoUgHSlxCc',
    appId: '1:32942490702:android:8c0f92417dd555e1aa2f1f',
    messagingSenderId: '32942490702',
    projectId: 'accompani-app',
    storageBucket: 'accompani-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQGyTH8_pFDbJUrGoWWw-murKb9VfKZzE',
    appId: '1:32942490702:ios:c6ea9a898fcc3ca9aa2f1f',
    messagingSenderId: '32942490702',
    projectId: 'accompani-app',
    storageBucket: 'accompani-app.appspot.com',
    iosBundleId: 'com.ios.accompani',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQGyTH8_pFDbJUrGoWWw-murKb9VfKZzE',
    appId: '1:32942490702:ios:4fbf5b3512d95a7baa2f1f',
    messagingSenderId: '32942490702',
    projectId: 'accompani-app',
    storageBucket: 'accompani-app.appspot.com',
    iosBundleId: 'com.example.accompani.RunnerTests',
  );
}
